config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/activities/my_bookings/', to: 'bookings#show_my_bookings', as: :my_bookings
  resources :areas do
    resources :activities do
      resources :bookings
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :activity
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @activity = Activity.find(params[:activity_id])
    @bookings = Booking.where(activity: @activity)
  end

  def new
    @activity = Activity.find(params[:activity_id])
    @booking = Booking.new
  end

  def create
    @activity = Activity.find(params[:activity_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.activity = @activity
    if @booking.save
      redirect_to my_bookings_path
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to my_bookings_path, notice: 'Booking has been successfully cancelled'
  end

  def show_my_bookings
    @area = current_user.area
    @bookings = Booking.where(user: current_user)
    @breadcrumbs = [{text: @area.name, url: area_path(@area)},
                    {text: 'Manage My Bookings', url: my_bookings_path}]
  end

  private

  def booking_params
    params.require(:booking).permit(:start, :end)
  end
end
#hello

app/views/bookings/index.html.erb
<div class="container">

<% @bookings.each do |booking| %>
  <%= booking.user  %>
  <%= booking.start  %>
  <%= booking.end  %>
<% end %>

</div>

app/views/bookings/new.html.erb
<h1>Book this activity</h1>

app/views/bookings/show_my_bookings.html.erb
<h2 class="bg-coral my-0" style="padding: 30px 0 30px 110px; font-weight: bolder; color: white;"> These are my bookings </h2>
<div class="container d-flex flex-column justify-content-center align-items-center">

<!-- Tabs to select activities -->
<ul class="list-inline tabs-underlined">
  <li class="tab-underlined">
    <%= link_to "Upcoming events", "#" %>
  </li>
  <li class="tab-underlined">
    <%= link_to "My created events", "#" %>
  </li>
</ul>

<div>
    <% @bookings.each do |booking| %>

    <div class="card-product card-short" style="margin:10px 0;">

      <%= link_to (image_tag activity_photo_url(booking.activity)), area_activity_path(booking.user.area, booking.activity) %>

      <div class="card-product-infos">
        <h2><%= link_to booking.activity.name, area_activity_path(booking.user.area, booking.activity)%></h2>
        <p><strong>Starts at:</strong> <%= booking.activity.starts_at.nil? ? 'Every Saturday 12:00 AM' : booking.activity.starts_at.strftime('%a, %d %b %Y %H:%M') %><br>
        <strong>Ends at: </strong> <%= booking.activity.ends_at.nil? ? 'Every Saturday 2:00 PM' : booking.activity.ends_at.strftime('%a, %d %b %Y %H:%M') %><br>
      </div>

      <div style="float: left; margin-left: 50px;">
        <%= link_to "View", area_activity_path(booking.user.area, booking.activity), class: 'btn btn-outline-warning' %>

        <%= link_to "Cancel", area_activity_booking_path(area_id: booking.user.area, activity_id: booking.activity.id, id: booking.id), class: 'btn btn-outline-dark', remote: true, method: :delete, data: {confirm: "Are you sure you want to cancel?"} %>
      </div>
    </div>
<% end %>
</div>

  <div class="input-buttons">
    <%= link_to "Back to activities list", area_activities_path(@area, @activities), class: "btn btn-outline-primary my-3" %>

    <%# link_to "Back to area", area_path(@area), class: "btn btn-outline-primary my-3 mx-3" %>
  </div>
</div>