config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/activities/my_bookings/', to: 'bookings#show_my_bookings', as: :my_bookings
  resources :areas do
    resources :activities do
      resources :bookings
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_avatar.html.erb
<div class="avatar-new" data-text="<%= user_initial(user) %>"<%= user_photo(user) %>></div>

app/views/shared/_breadcrumbs.html.erb
<%# <div class="breadcrumbs-container"> %>
  <div class="breadcrumbs">
    <ul>
      <li><a href="/">Home</a></li>
      <% if @breadcrumbs %>
      <% @breadcrumbs.each_with_index do |crumb, index| %>
      <li><a href="<%= crumb[:url] %>"><%= crumb[:text] %></a></li>
      <% end %>
      <% end%>
    </ul>
  </div>
<%# </div> %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">

    © 2022 Neighborino, Inc. All rights reserved

  </div>
</footer>

app/views/shared/_nav-avatar.erb
<div id="navbarDropdown" class="avatar-new dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-text="<%= user_initial(user) %>"<%= user_photo(user) %>></div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-3">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "" %>
      <span class="logo-type">Neighborino</span>
      <p class="logo-phrase">Discover your local community</p>
      </div>
    <% end %>
    <div class="collapse navbar-collapse">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <% unless @area.nil? %>
          <li id="host-button" class="nav-item"> <%= link_to "Host an activity", new_area_activity_path(@area, @activity) %></li>
           <li id="my-activities-button" class="nav-item"> <%= link_to "My booked activities", my_bookings_path %> </li>
          <% end %>
          <li class="nav-item dropdown">
            <%= render 'shared/nav-avatar', user: current_user %>
            <%# image_tag "https://res.cloudinary.com/dqat8a2hi/image/upload/v1645530508/Space-BNB/yuJKnlCNTN2sabHfSPhr_CyberPug_1-4_jcayx0.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My account", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
    </div>
  </div>
</div>

<%= render 'shared/breadcrumbs', breadcrumbs: @breadcrumbs %>