config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/activities/my_bookings/', to: 'bookings#show_my_bookings', as: :my_bookings
  resources :areas do
    resources :activities do
      resources :bookings
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :users
  has_many :activities, through: :users
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    unless params['location']
      @areas = Area.limit(6).order("RANDOM()")
    else
      @areas = Area.near(params['location'], 2)
    end
      @markers = @areas.geocoded.map do |area|
      {
        lat: area.latitude,
        lng: area.longitude
      }
    end
  end

  def show
    #@activities = Activity.first(6)
    @area = Area.find(params[:id])
    #@activities = Activity.includes(:user).where(user: {area: @area}).limit(6)
    @activities = Activity.includes(:user).where(user: {area_id: @area.id})

    @breadcrumbs = [{text: @area.name, url: area_path(@area)}]
  end
end

app/views/areas/index.html.erb
  <%# <div id="map-container"> %>
    <div id="map"
      style="width: 100%; height: 300px;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  <%# </div> %>



<div class="content">
  <div class="area-card-container mt-4 container">
    <% @areas.each do |area| %>
     <%= link_to area_path(area) do %>
      <div class="card-area">
      <img src="<%= area_image_url(area) %>" />
      <div class="card-area-infos">
        <div>
          <h2><%= area.name %></h2>
          <!--
          <p><%= area.address %></p>
          -->
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
  </div>

  <br> <br>

</div>

app/views/areas/show.html.erb
<div class="area-title bg-coral" style="padding: 30px 0 30px 0;">
  <h1 style="font-weight: bolder;">Things to do in <%= @area.name %></h1>
</div>


<div class="headerino bg-green">
  <h2 class="headerino-lm" style="margin-left: 100px; font-weight: bolder;">Categories</h2>
</div>
<br>

<div class="container">

  <div class="cards">
  <%= link_to "#{area_activities_path(@area)}?query=sports" do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= category_image('sports') %>')">
     Sports
    </div>
   <% end %>

  <%= link_to "#{area_activities_path(@area)}?query=gardening" do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= category_image('gardening') %>')">
      Gardening
    </div>
  <% end %>

  <%= link_to "#{area_activities_path(@area)}?query=social" do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= category_image('social') %>')">
      Social
    </div>
  <% end %>

  <%= link_to "#{area_activities_path(@area)}?query=crafts" do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= category_image('crafts') %>')">
      Crafts
    </div>
  <% end %>

  <%= link_to "#{area_activities_path(@area)}?query=exchange" do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= category_image('exchange') %>')">
      Exchange
    </div>
  <% end %>

  <%= link_to "#{area_activities_path(@area)}?query=information" do %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= category_image('info') %>')">
      Info
    </div>
  <% end %>

  </div>

</div>

<div class="headerino bg-blue">
  <h2 class="headerino-lm" style="margin-left: 100px; font-weight: bolder;">Recently added activities</h2>
</div>

<div class="container">

  <div class="cards-activity">
    <% @activities.each_with_index do |activity, index| %>
    <%= link_to area_activity_path(@area, activity) do %>
    <div class="card-product activity-cards">
      <img src="<%= activity_photo_url(activity) %>" />
      <div class="card-product-infos">
        <h2><%= activity.name.capitalize %></h2>
        <p><%= activity_description_cap(activity, 85) %></p>
      </div>
    <div>
    <%= render 'shared/nav-avatar', user: activity.user %>

     <%# image_tag "https://res.cloudinary.com/dqat8a2hi/image/upload/v1645530508/Space-BNB/yuJKnlCNTN2sabHfSPhr_CyberPug_1-4_jcayx0.jpg", id: "avatar-bordered" %>
    </div>
    </div>
    <% end %>
    <% end %>
  </div>

    <br>
    <%# link_to "Back to areas", areas_path, class: "btn btn-outline-primary my-3" %>

</div>

<%# render 'shared/breadcrumbs', breadcrumbs: @breadcrumbs %>
<%# github acting up again %>