config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get '/activities/my_bookings/', to: 'bookings#show_my_bookings', as: :my_bookings
  resources :areas do
    resources :activities do
      resources :bookings
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord


  belongs_to :user
  has_many :users, through: :bookings
  has_many :bookings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_one_attached :photo, dependent: :destroy

  include PgSearch
  include PgSearch::Model

  pg_search_scope :search,
  against: [ :tags, :name, :description ],
    using: {
      tsearch: { prefix: true, any_word: true } # <-- now `superman batm` will return something!
    }
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_area
  before_action :set_activity, only: [:show, :edit, :update]

  def index
    #category = params[:query]
    if params[:query].present?
      #@activities = Activity.search(params[:query])
      @activities = Activity.includes(:user).where(user: {area: @area}).search(params[:query])
    else
      #@activities = Activity.first(12)
      #@activities = Activity.where(user: {area: {id: @area.id}})
      @activities = Activity.includes(:user).where(user: {area: @area}).limit(24)
      #@activities = Activity.search(params[:query])
      #activities = Activity.where("name ILIKE ?", "%#{category}%")
    end
    @markers = @activities.geocoded.map do |activity|
      {
        lat: activity.latitude + ((rand - 0.5) * 0.02),
        lng: activity.longitude + ((rand - 0.5) * 0.04)
      }
    end
    @breadcrumbs = [{text: @area.name, url: area_path(@area)},
                    {text: 'Activities', url: area_activities_path(@area)}]
  end

  def show
    @booking = Booking.new
    @breadcrumbs = [{text: @area.name, url: area_path(@area)},
                    {text: 'Activities', url: area_activities_path(@area)},
                    {text: @activity.name, url: area_activity_path(@area, @activity)}]
  end

  def edit
  end

  def update
    if @activity.update(activity_params)
      redirect_to activity_path(@activity), notice: 'Activity was successfully updated.'
    else
      render :edit
    end
  end

  def new
    @activity = Activity.new
    @activity.address = @area.address

    @breadcrumbs = [{text: @area.name, url: area_path(@area)},
      {text: 'Activities', url: area_activities_path(@area)},
      {text: 'Host an activity', url: new_area_activity_path(@area, @activity)}]
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    # @activity.area = @activity
    if @activity.save
      redirect_to area_activity_path(@area, @activity)
      #redirect_to area_activities_path
    else
      render :new
    end
  end

  private

  def set_area
    @area = Area.find(params[:area_id])
  end

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:name, :address, :photo, :description, :starts_at, :ends_at)
  end
end

app/views/activities/index.html.erb
<div class="index-container">
  <div class="activities-index-left">
    <div class="headerino bg-blue py-4">
        <div class="left-container d-flex flex-column">

      <h2 style="font-weight: bolder;">Activities in <%= @area.name %></h2>
</div>
    </div>
    <div class="left-container d-flex flex-column align-items-center">

    <div class="w-100 d-flex flex-column align-items-start">
      <%# link_to "Back to area", area_path(@area), class: "btn btn-outline-primary my-3" %>
    </div>

      <ul class="list-inline tabs-underlined">
        <li class="tab-underlined">
          <%= link_to "Sports", "#{area_activities_path(@area)}?query=sports", class: (params[:query]&.include?("sports") ? "active" : "inactive") %>
        </li>
        <li class="tab-underlined">
          <%= link_to "Gardening", "#{area_activities_path(@area)}?query=gardening", class: (params[:query]&.include?("gardening") ? "active" : "inactive") %>
        </li>
        <li class="tab-underlined">
          <%= link_to "Social", "#{area_activities_path(@area)}?query=social", class: (params[:query]&.include?("social") ? "active" : "inactive") %>
        </li>
        <li class="tab-underlined">
          <%= link_to "Crafts", "#{area_activities_path(@area)}?query=crafts", class: (params[:query]&.include?("crafts") ? "active" : "inactive") %>
        </li>
        <li class="tab-underlined">
          <%= link_to "Exchange", "#{area_activities_path(@area)}?query=exchange", class: (params[:query]&.include?("exchange") ? "active" : "inactive") %>
        </li>
        <li class="tab-underlined">
          <%= link_to "Info", "#{area_activities_path(@area)}?query=information", class: (params[:query]&.include?("info") ? "active" : "inactive") %>
        </li>
      </ul>

      <div class="w-100">
        <% @activities.each_with_index do |activity, index| %>
          <%= link_to area_activity_path(@area, activity) do %>
            <div class="card-product activity-cards">
              <img src="<%= activity_photo_url(activity) %>" />
              <div class="card-product-infos">
                <h2 id="activity-title"><%= activity.name.capitalize %></h2>
                 <p><%= activity_description_cap(activity, 85) %></p>
              </div>
              <div>
              <%= render 'shared/nav-avatar', user: activity.user %>
              <%# image_tag "https://res.cloudinary.com/dqat8a2hi/image/upload/v1645530508/Space-BNB/yuJKnlCNTN2sabHfSPhr_CyberPug_1-4_jcayx0.jpg", id: "avatar-bordered-index" %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="map-box-vertical">
    <div id="sticky-map"
      style="width: 100%; height: 100vh;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
      <%# <img  src='https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/1.346,48.8595,11.72,0,0/1200x400?access_token=pk.eyJ1Ijoic2FqaWZpbyIsImEiOiJjbDA5amVzcDMwMGw3M2JwdDI0M3ZwbXVmIn0.87lNDe_z7JyUZ-9LyvJn1w'></div> %>
  </div>
</div>

app/views/activities/new.html.erb
<div class="container">
</div>

<div class="d-flex card-area-new bg-coral">
  <h2 class="text-start">Name your event</h2>
  <%= simple_form_for [ @area, @activity ] do |f| %>
  <%= f.input :name, label: false, input_html: {class: "n-text-input"}  %>
</div>

<div class="d-flex card-area-new bg-blue right-side">
  <h2 class="text-start">Where is it taking place?</h2>
<%= f.input :address, label: false, input_html: {class: "n-text-input"}  %>
</div>

<div class="d-flex card-area-new bg-green">
  <h2 class="text-start">Choose a date</h2>
  <div class="d-flex">
      <%= f.input :starts_at, as: :string, required: true, input_html: {class: "datepicker n-text-input"} %>
      <%= f.input :ends_at, as: :string, required: true, input_html: {class: "datepicker n-text-input"} %>
  </div>
</div>

<div class="d-flex card-area-new bg-yellow right-side">
  <h2 class="text-start">Description</h2>
  <%= f.input :description, label: false, input_html: {class: "activity-description-input n-text-input", :size=>"10"} %>
</div>

<div class="d-flex card-area-new bg-coral">
  <h2 class="text-start">Upload pictures</h2>
    <%= f.input :photo, multiple: true, as: :file, label: false, input_html: {class: "n-text-input"} %>
</div>

<div class="d-flex card-area-new bg-blue right-side">
  <h2 class="text-start">Add tags</h2>
  <p>This will help neighborinos find your activity</p>
  <%= f.input :tags, as: :check_boxes, legend_tag: false, input_html: { class: "tag-selector" },item_wrapper_class: 'tag-item', collection: ['Sports','Gardening','Social','Crafts','Exchange','Info'], wrapper: :vertical_collection_inline %>
</div>

<div class="d-flex card-area-new bg-green">
  <%= f.submit "Diddly that activity!", class: "submit-button-area btn btn-primary" %>
  <% end %>
</div>

<%# <div class="card-area-back bg-yellow d-flex justify-content-center"> %>
  <%# link_to "Back to activities list", area_activities_path(@area, @activities), class: "btn btn-outline-primary my-3 mx-2" %>

  <%# link_to "Back to area", area_path(@area), class: "btn btn-outline-primary my-3 mx-2" %>
<%# </div> %>

<%# hello %>

app/views/activities/show.html.erb
<div class="headerino bg-blue">
  <h2 class="headerino-lm" style="font-weight: bolder; padding-left: 16px;"><%= @activity.name.capitalize %></h2>
  <p style="padding-left: 16px;"><%= "#{@activity.address} - organised by" %> <strong><%= "#{@activity.user.first_name} #{@activity.user.last_name}" %></strong></p>
</div>

<div class="container">

<div>
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">

        <img src="<%= activity_photo_url(@activity) %>" class="d-block w-100" height="500px" style="object-fit:cover;" alt="...">
      </div>
      <div class="carousel-item">
        <img src="<%= activity_photo_url(@activity) %>" class="d-block w-100" height="500px" style="object-fit:cover;" alt="...">
      </div>
      <div class="carousel-item">
        <img src="<%= activity_photo_url(@activity) %>" class="d-block w-100" height="500px" style="object-fit:cover;" alt="...">

      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


<div class="headerino bg-green">
  <h3 class="headerino-lm" style="font-weight: bolder;">Details</h3>
</div>

<div><p style="margin: 0 auto; padding-left: 15px;"><%= @activity.description %></p></div>

<div>
  <h4 class="text-left sub-heading" style="padding-left: 15px; font-weight: bolder;">Location</small></h4>
  <p style="margin: 0 auto; padding-left: 15px;">Wandle Park, <%= @activity.user.area.address %></p>
</div>

<div class="d-flex justify-content-between">
  <div class="col-6">
      <h4 style="padding-left: 15px; font-weight: bolder;"><small>Start date</small></h4>
      <p style="padding-left: 15px; "><%= @activity.starts_at.nil? ? 'Every Saturday 12:00 AM' : @activity.starts_at.strftime('%a, %d %b %Y %H:%M') %></p>
  </div>
  <div class="col-6">
    <h4 style="font-weight: bolder;"><small>End date</small></h4>
    <p><%=  @activity.ends_at.nil? ? 'Every Saturday 2:00 PM' : @activity.ends_at.strftime('%a, %d %b %Y %H:%M') %></p>
  </div>
</div>


   <!-- create new @booking, simple form, submit-->
<div class="input-buttons">
<%= simple_form_for(@booking, url: area_activity_bookings_path(@area, @activity)) do |f| %>
  <%= f.input :start, as: :hidden, value: @activity.starts_at %>
  <%= f.input :end, as: :hidden, value: @activity.ends_at %>
  <%= f.button :submit, "Book this activity", class: "btn btn-outline-primary my-3" %>
<% end %>
</div>


<%# link_to "Back to activities list", area_activities_path, class: "btn btn-outline-primary my-3" %>

<%# link_to "Back to area", area_path(@area), class: "btn btn-outline-primary my-3 mx-3" %>

</div>
<br>

<%# helo %>